### ISSUE TITLE
invert colorScale in grayscale theme and remove "#ffffff"

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-core#117]
Grayscale theme should start with the same color as all the grayscale defaults. White should be removed because it causes invisible elements on white backgrounds which many people will use when they are setting up a project / testing out victory. 

@paulathevalley What are your thoughts on this?

**Comment by paulathevalley** [comment]
Hey! Totally makes sense to optimize for the most common use case and avoid white on white. If I am not misunderstanding, yes, it makes to me that if most of the defaults start at black, then the scale should start at black too. 

My only guiding thought is the scale would be optimized for the greatest contrast between two adjacent colors depending on the number of colors, as demonstrated in the brewer palette screenshot here: 
https://github.com/FormidableLabs/victory-core/issues/68#issuecomment-225728908 

On closer inspection, removing #fff is only a problem when there are 8 or 9 colors. Does the current grayscale color theme go that high? 

Or, is the problem actually with both the first (#fff) and second (#f7f7f7) swatches? Hmm, how about trying out row 8 or 9 without the white?! Since that technically wouldn't have as much contrast between adjacent colors as the rows above it, it may not work very well. In which case, more research/testing is required!

(answering all possible questions as always)

**Comment by boygirl** [comment]
Hey! I think probably both #fff and #f7f7f7 should probably go. colorScales are set up to repeat anyway, and the close color values should only be an issue if the data isn't laid out sequentially _i.e._ and bunch of crazy lines or scatter points, not a nice neat stacked bar / stacked area / grouped bar. Hopefully people take advantage of symbols and stroke styles instead of relying only on color. 

Optimizing the colorScale prop for the number of colors requested is still an open ticket. Still scratching my head over that one a little, especially with the complication of themes...
