### ISSUE TITLE
onEnter after hook not being called (on VictoryScatter animations at least)

### ISSUE THREAD

**Issue by richsilv** [FormidableLabs/victory-core#85]
I have a VictoryScatter chart which is animating between data-sets which have different numbers of points.  If the chart data is updated to a set with more points, the new points do not appear (although I can make them do so by hovering as that overwrites the styles on them).

You can see from investigating the nodes in the console that they have opacity set to 0.  Further, this is because the `defaultTransition` for the VictoryScatter has a `before` hook which sets the new points' opacity to zero, and an `after` hook which is supposed to set them back to opacity 1.

Explicitly passing in hooks to overwrite these makes it fairly clear that the `after` hook isn't being called at all.

**Comment by boygirl** [comment]
@richsilv sorry for the delay. I haven't been able to reproduce this issue. I made a gif with the `before` hook setting the opacity to 0.3 instead of zero so it's easier to see.

![onenter](https://cloud.githubusercontent.com/assets/3719995/17081499/b4523a7a-5110-11e6-98d4-15dbdd6a9822.gif)

The animate prop for this chart looks like 
```
animate={{
   onExit: {
     duration: 500,
     before: () => ({opacity: 0.3})
    },
    onEnter: {
      duration: 500,
      before: () => ({ opacity: 0.3 }),
      after: (datum) => ({ opacity: datum.opacity || 1 })
   }
}}
```
Can I see what your code looks like?
